### ISSUE TITLE
Build fails due to not having python in the slim image

### ISSUE THREAD

**Issue by Page-** [balena-io-projects/simple-server-node#9]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_12i5)

**Comment by shaunmulligan** [comment]
@Page- I purposefully chose the slim image, so the first push experience isn't so long. I also detail in the docs [[here](https://docs.resin.io/raspberrypi/nodejs/getting-started/#let-s-dive-into-the-code)] about what `:slim` means and what one should do if they want to install native dependencies. I guess we can switch to the full image, but its more than doubles the push time and makes things really unbearable in my opinion.

**Comment by Page-** [comment]
This came up as an issue in [gitter](https://gitter.im/resin-io/chat?at=58ae0c2bde50490822018b21) again today.  It's definitely a hard trade-off though, because if the first push takes too long then people might not even get to the point of caring about python :|

**Comment by garethtdavies** [comment]
No longer relevant in this repo.
